### ISSUE TITLE
机器人领地内错误刷屏

### ISSUE THREAD

**Issue by McWhirl-V** [StarWishsama/SlimefunBlackList#2]
版本: 1.0.2 efac5db
slimefun: 200407 nightly

机器人在领地内会一直刷屏
![86584111997749C512A8ED777069C765](https://user-images.githubusercontent.com/40943282/78662317-c29a2980-7902-11ea-9cb8-19d90ea4ef5c.png)
但虽然刷屏 机器人仍然可继续工作
领地外正常
后台目前没有报错

**Comment by StarWishsama** [comment]
领地是自己的还是什么
